# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dab',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
